from prometheus_client import Counter, Histogram, Gauge, generate_latest, REGISTRY
from prometheus_client.multiprocess import MultiProcessCollector

query_total = Counter("machineguru_query_total", "Total queries processed", ["status"])
query_duration = Histogram(
    "machineguru_query_duration_seconds",
    "Query execution time",
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)
query_tokens = Counter("machineguru_query_tokens_total", "Tokens generated by LLM")
query_cache_hits = Counter("machineguru_query_cache_hits_total", "Query cache hits")
query_cache_misses = Counter("machineguru_query_cache_misses_total", "Query cache misses")

ingestion_total = Counter("machineguru_ingestion_total", "Documents ingested", ["status"])
ingestion_duration = Histogram(
    "machineguru_ingestion_duration_seconds",
    "Document ingestion time",
    buckets=[1.0, 5.0, 10.0, 30.0, 60.0, 120.0],
)
ingestion_chunks = Counter("machineguru_ingestion_chunks_total", "Chunks created")

embedding_duration = Histogram(
    "machineguru_embedding_duration_seconds",
    "Embedding generation time",
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0],
)
embedding_cache_hits = Counter("machineguru_embedding_cache_hits_total", "Embedding cache hits")

memory_usage = Gauge("machineguru_memory_mb", "Process memory in MB", ["type"])
gpu_memory_usage = Gauge("machineguru_gpu_memory_mb", "GPU memory in MB")
gpu_utilization = Gauge("machineguru_gpu_util_percent", "GPU utilization percent")

concurrent_llm = Gauge("machineguru_concurrent_llm", "Concurrent LLM requests")
concurrent_embeddings = Gauge("machineguru_concurrent_embeddings", "Concurrent embedding requests")
concurrent_qdrant = Gauge("machineguru_concurrent_qdrant", "Concurrent Qdrant requests")

model_loaded = Gauge("machineguru_model_loaded", "Model loaded state", ["model_name"])

request_total = Counter(
    "machineguru_request_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"],
)
request_duration = Histogram(
    "machineguru_request_duration_seconds",
    "HTTP request duration",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)
active_requests = Gauge("machineguru_active_requests", "Currently active requests")
ollama_request_duration = Histogram(
    "machineguru_ollama_request_duration_seconds",
    "Ollama request duration",
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)
qdrant_request_duration = Histogram(
    "machineguru_qdrant_request_duration_seconds",
    "Qdrant request duration",
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0],
)


def metrics_endpoint():
    return generate_latest(REGISTRY)
